name: shell

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Would be nice to have a test script to validate the output
      - name: Run the main Shell script to confirm there are no major issues
        run: sh run.sh
